/*
 * AttenuationCoefficient.java
 *
 * Created on 9 de Março de 2010, 10:54
 */

package com.usp.ipen.acs.Attenuation_Correction_SPECT.source;

import com.usp.ipen.acs.Attenuation_Correction_SPECT.ACS_;
import com.usp.ipen.acs.Attenuation_Correction_SPECT.io.Open;
import ij.process.ImageProcessor;
import javax.swing.JOptionPane;

/**
 *
 * @author  fmassicano
 */
public class ParameterToAttenuationCorrection extends javax.swing.JFrame{

    private static float coef,
                         size,
                         proj;
    private static String pathDirectory;
    private static String coef_pathDirectory;
    private AcHomHet ca ;
    private boolean lock_output;
    private boolean lock_coef, butcoef;
    private Open open = new Open();
    private Open op = new Open();
    private ImageProcessor ip;

    /** Creates new form AttenuationCoefficient */
    public ParameterToAttenuationCorrection() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setTitle("Parameters for Attenuation Correction");
        setBounds(new java.awt.Rectangle(400, 400, 0, 0));
        setResizable(false);

        jButton1.setFont(new java.awt.Font("Dialog", 0, 12));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 0, 12));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Output file", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Dialog", 0, 12));

        jButton5.setFont(new java.awt.Font("Dialog", 0, 12));
        jButton5.setText("Choose");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Additional Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel4.setText("Attenuation Coefficient:");

        jTextField12.setFont(new java.awt.Font("Dialog", 0, 12));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel2.setText("Size of pixel:");

        jTextField13.setFont(new java.awt.Font("Dialog", 0, 12));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel5.setText("Projections:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3)
                            .addComponent(jTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

   jButton1.requestFocus();

    if (!lock_output) {
        JOptionPane.showMessageDialog(null, "File text", "ERRO", JOptionPane.ERROR_MESSAGE);
        return;
    }
   
    try {

        if (true) {

            // Homogeneous

            if (jTextField12.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Attenuation Coefficient", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jTextField13.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Pixel of size", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jTextField3.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Projections", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (Float.parseFloat(jTextField12.getText()) <= 0) {
                JOptionPane.showMessageDialog(null, "Attenuation Coefficient", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (Float.parseFloat(jTextField13.getText()) <= 0 ) {
                JOptionPane.showMessageDialog(null, "Pixel of size", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (Float.parseFloat(jTextField3.getText()) <= 0) {
                JOptionPane.showMessageDialog(null, "Projections", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            }

            coef = Float.parseFloat(jTextField12.getText()); // Atribui a variável coef o coeficinte de atenuação do meio

            size = Float.parseFloat(jTextField13.getText()); // Atribui a variável size o tamanho do pixel

            proj = Float.parseFloat(jTextField3.getText()); // Atribui a variável proj o número de projeções

            ParameterToAttenuationCorrection.this.setVisible(false); // fecha o jframe de CorrectioAttenuation

            ca = new AcHomHet(ACS_.getCopy(), "homogeneous"); // construir o objeto que fará a correção

        } else {

            // Heterogeneous

            if (!lock_coef) {
                JOptionPane.showMessageDialog(null, "It is necessary to put the Maps of Attenuation", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (!butcoef) {
                JOptionPane.showMessageDialog(null, "It is necessary Build Map", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jTextField13.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Pixel of size", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jTextField3.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Projections", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            }else if (Float.parseFloat(jTextField13.getText()) <= 0 ) {
                JOptionPane.showMessageDialog(null, "Pixel of size", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (Float.parseFloat(jTextField3.getText()) <= 0) {
                JOptionPane.showMessageDialog(null, "Projections", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            }

            size = Float.parseFloat(jTextField13.getText()); // Atribui a variável size o tamanho do pixel

            proj = Float.parseFloat(jTextField3.getText()); // Atribui a variável proj o número de projeções

            ParameterToAttenuationCorrection.this.setVisible(false); // fecha o jframe de CorrectioAttenuation

            ca = new AcHomHet(ACS_.getCopy(), "heterogeneous"); // construir o objeto que fará a correção

        }

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Number", "ERRO", JOptionPane.ERROR_MESSAGE);
    }

}//GEN-LAST:event_jButton1ActionPerformed

private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed

   jButton1.requestFocus();

    if (!lock_output) {
        JOptionPane.showMessageDialog(null, "File text", "ERRO", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {

        if (true) {

            // Homogeneous

            if (jTextField12.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Attenuation Coefficient", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jTextField13.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Pixel of size", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jTextField3.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Projections", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (Float.parseFloat(jTextField12.getText()) <= 0) {
                JOptionPane.showMessageDialog(null, "Attenuation Coefficient", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (Float.parseFloat(jTextField13.getText()) <= 0 ) {
                JOptionPane.showMessageDialog(null, "Pixel of size", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (Float.parseFloat(jTextField3.getText()) <= 0) {
                JOptionPane.showMessageDialog(null, "Projections", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            }

            coef = Float.parseFloat(jTextField12.getText()); // Atribui a variável coef o coeficinte de atenuação do meio

            size = Float.parseFloat(jTextField13.getText()); // Atribui a variável size o tamanho do pixel

            proj = Float.parseFloat(jTextField3.getText()); // Atribui a variável proj o número de projeções

            ParameterToAttenuationCorrection.this.setVisible(false); // fecha o jframe de CorrectioAttenuation

            ca = new AcHomHet(ACS_.getCopy(), "homogeneous"); // construir o objeto que fará a correção

        } else {

            // Heterogeneous

            if (!lock_coef) {
                JOptionPane.showMessageDialog(null, "It is necessary to put the Maps of Attenuation", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (!butcoef) {
                JOptionPane.showMessageDialog(null, "It is necessary Build Map", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jTextField13.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Pixel of size", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jTextField3.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Projections", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            }else if (Float.parseFloat(jTextField13.getText()) <= 0 ) {
                JOptionPane.showMessageDialog(null, "Pixel of size", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (Float.parseFloat(jTextField3.getText()) <= 0) {
                JOptionPane.showMessageDialog(null, "Projections", "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            }

            size = Float.parseFloat(jTextField13.getText()); // Atribui a variável size o tamanho do pixel

            proj = Float.parseFloat(jTextField13.getText()); // Atribui a variável proj o número de projeções

            ParameterToAttenuationCorrection.this.setVisible(false); // fecha o jframe de CorrectioAttenuation

            ca = new AcHomHet(ACS_.getCopy(), "heterogeneous"); // construir o objeto que fará a correção

        }

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Number", "ERRO", JOptionPane.ERROR_MESSAGE);
    }

}//GEN-LAST:event_jButton1KeyPressed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    /* Finaliza o programa */
    ParameterToAttenuationCorrection.this.setVisible(false);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
   
    open.setTitle("Select out file text");
    
    open.selectOutFile();
    
    pathDirectory = open.getPathDirectory();
    
    jTextField10.setText(pathDirectory);
    
    lock_output = open.getLock_Open_File();
    
    open.setLock_Open_File(false);
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
    open.setTitle("Select out file text");
    
    open.selectOutFile();
    
    pathDirectory = open.getPathDirectory();
    
    jTextField10.setText(pathDirectory);
    
    lock_output = open.getLock_Open_File();
    
    open.setLock_Open_File(false);
}//GEN-LAST:event_jButton5KeyPressed

    public static float getCoef() {
        return coef;
    }

    public static float getProj() {
        return proj;
    }

    public static float getSizePixels() {
        return size;
    }
    
    public static String getPathDirectory(){
        return pathDirectory;
    }

    public static void main(String[] args){

        ParameterToAttenuationCorrection pa = new ParameterToAttenuationCorrection();
        pa.setVisible(true);

    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
